[package]
name = "tyrus_analyzer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tyrus_diagnostics = { path = "../tyrus_diagnostics" }
tyrus_di = { path = "../tyrus_di" }
tyrus_decorator_kinds = { path = "../tyrus_decorator_kinds" }
swc_ecma_ast = "29.0.0"
swc_ecma_visit = "29.0.0"
swc_common = { version = "26.0.0", features = ["tty-emitter"] }
miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console = "0.16"

[dev-dependencies]
swc_ecma_parser = "45.1.1"

[lints]
workspace = true
