[package]
name = "tyrus_cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "tyrus"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
tokio = { version = "1.52", features = ["full"] }
tyrus_orchestrator = { path = "../tyrus_orchestrator" }
tyrus_common = { path = "../tyrus_common" }
tyrus_analyzer = { path = "../tyrus_analyzer" }
tyrus_diagnostics = { path = "../tyrus_diagnostics" }
console = "0.15"
indicatif = "0.18"

[lints]
workspace = true
